---
- name: install apt-transport-https
  apt:
    pkg: "{{item}}"
    update-cache: yes
    cache_valid_time: 86400
  with_items:
    - apt-transport-https
    - python-pycurl

- name: add the official rabbitmq repository's key
  apt_key:
    url: "https://www.rabbitmq.com/rabbitmq-signing-key-public.asc"
    state: present

- name: add rabbitmq repository
  apt_repository:
    repo: "deb http://www.rabbitmq.com/debian/ testing main"
    state: present

- name: install rabbitmq
  apt:
    pkg: rabbitmq-server
    update-cache: yes

- name: enable rabbitmq service
  service:
    name: rabbitmq-server
    enabled: yes

- name: enable the rabbitmq_management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
