---
- name: add the official rabbitmq repository's key
  apt_key:
    url: "https://www.rabbitmq.com/rabbitmq-release-signing-key.asc"
    state: present
  tags:
  - rabbitmq

- name: add rabbitmq repository
  apt_repository:
    repo: "deb http://www.rabbitmq.com/debian/ testing main"
    state: present
  register: rabbitmq_added
  tags:
  - rabbitmq

- name: apt update cache
  apt:
    update_cache: yes
  when: rabbitmq_added.changed
  tags:
  - rabbitmq

- name: install rabbitmq
  apt:
    pkg: rabbitmq-server
    state: present
  tags:
  - rabbitmq

- name: enable rabbitmq service
  service:
    name: rabbitmq-server
    enabled: yes
  tags:
  - rabbitmq

- name: enable the rabbitmq_management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  tags:
  - rabbitmq

- name: add rabbitmq vhosts
  rabbitmq_vhost:
    name={{ item.name }}
    node={{ item.node | default('rabbit') }}
    tracing={{ item.tracing | default('no') }}
    state={{ item.state | default('present') }}
  with_items: "{{ rabbitmq_vhosts }}"
  tags:
  - rabbitmq

- name: add rabbitmq users
  rabbitmq_user:
    user={{ item.user }}
    password={{ item.password }}
    vhost={{ item.vhost | default('/', false) }}
    node={{ item.node | default('rabbit') }}
    tags={{ (item.tags | default('')) | join(',') }}
    configure_priv={{ item.configure_priv | default('.*') }}
    read_priv={{ item.read_priv | default('.*') }}
    write_priv={{ item.write_priv | default('.*') }}
    state={{ item.state | default('present') }}
    force={{ item.force | default('yes') }}
  with_items: "{{ rabbitmq_users }}"
  tags:
  - rabbitmq

- name: create main rabbitmq conf file
  template:
    src: rabbitmq.conf
    dest: "{{ rabbitmq_conf_path }}"
    owner: "rabbitmq"
    group: "rabbitmq"
  notify: restart rabbitmq
  tags:
  - rabbitmq
  
- include: erlang-cookie.yml
  when: (rabbitmq_erlang_cookie is defined)
    and (rabbitmq_erlang_cookie is not none)
  tags:
  - rabbitmq
